name: Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3.1.1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -r requirements_dev.txt
    - name: black
      run: |
        black --check pyeight
    - name: isort
      run: |
        isort --check pyeight
    - name: pylint
      run: |
        pylint pyeight
    - name: mypy
      run: |
        mypy pyeight
